name: test and build luascli app on push

on: [push]
jobs:
  build-luascli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Setup environment
        run: >-
          make init

      - name: Analyse the code for syntax and vulnerabilities
        run: >-
          make check        

      - name: Run unit tests
        run: >-
          make test

      - name: Build luascli
        run: >-
          make build