name: release candidates

on:
  push:
    tags:     
      - '*-rc*'

jobs:
  release-rc-luascli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Build luascli
        run: >-
          make build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          directory: ./
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-luascli
          fail_ci_if_error: true
          verbose: true          

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
          repository_url: https://test.pypi.org/legacy/          